server:
   port: 9191
spring:
   jpa:
      hibernate:
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
         hibernate:
            show_sql: true
   application:
      name: dta-authentication  
         
logging:
   level:
      org:
         hibernate:
            type: trace
            
security:
   oauth2:
      client:
         clientId: dtaService
         clientSecret: dtaServiceSecret
         accessTokenUri: http://localhost:9191/oauth/token
         userAuthorizationUri: http://localhost:9191/oauth/authorize
      resource:
         token-info-uri: http://localhost:9191/oauth/check_token  
         
##------ Eureka Discovery ------
eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      register-with-eureka: true
      fetch-registry: true
   instance:
      preferIpAddress: true
      
      
      
      
      